--- 
title: "02.521: Urban Data & Methods I: Computational Urban Analysis"
author: "Ate Poorthuis"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
---
# Syllabus

## Class Schedule
**January Term 2020**  
**Tue 12.30-2pm** Think Thank 7 (1.409)  
**Thu 11.00-12.30pm** Think Thank 17 (2.202)  
Office Hours: By appointment  

## Course Description

This course focuses on quantitative and computational approaches to urban analytics and data science. It exposes students to new ways of collecting large datasets (“big data”) and innovative methods of analysing such datasets. It draws on both more conventional methods such as (spatial) statistics, as well as how to appropriately use methods from data science and machine learning within an urban context.

## Format
The course is structured around two 1.5 hour classes per week that integrate lecture, discussion and in-class activities and exercises in an interactive manner. The class is further structured around 6 blocks (each lasting two weeks).

## Expectations
Students are expected to be present and actively participate in each class, as well as on the class online forum (Slack). Before coming to class, you will have read the assigned readings and you are coming to class prepared to participate in discussion and exercises. 

You are also expected to produce your own work, whether individually or in groups. Do not copy work from the internet or other published sources without proper citations. This is plagiarism and if a student is found to be doing so, he or she will be subject to disciplinary measures including potentially failing the course.

## Assessment
There will be a variety of assessments throughout the semester. Emphasis is on your performance overall, with relatively low weight placed on individual items. Continued participation throughout the semester will enable you to do well in this course.

| Assessment Items                          | Percentage | Period          |
|-------------------------------------------|------------|-----------------|
| Class Participation                       | 15%        | Throughout term |
| Assignments (six)                         | 45%        | Throughout term |
| Final Project                             | 40%        | Week 14         |

### Assignments
Each block consists of a series of exercises that culminate in an assigment/report that will be due before the start of the next block (Monday 23.59).

### Final Project
For the final project, you will develop conduct a computational analysis of a topic and dataset of your own choice. This is an opportunity to explore (an aspect of) your final term project in more detail -- or take a deep-dive in a topic or dataset that you're interested in. You can choose to use already existing datasets, or collect your own but you must use one or more computational methods to help answer your reseach question. In Week 6, you will hand in a research proposal of a maximum of 1000 words. It should discuss your motivation for the project; its objectives and research question; data requirements (does the data already exist? where do you get it from? does it need a lot of post-processing); and the methods you plan on utilizing. The remainder of the term is spent on collecting and analyzing data. A prototype of your analysis is due at the end of Week 13 and the final version at the end of Week 14. You are required to hand in both the code, a written paper and (where appropriate) visualizations as part of your Github repository. You can do this in a single form factor through one or more RMarkdown documents. 

## Deadlines
Deadlines are as noted in the course syllabus or on the specific assignment. If something is due on a specific date, you have until midnight on that day to submit the assignment.

## Software
We will use R, RStudio and a series of packages (most of them compatible with the [Tidyverse](https://www.tidyverse.org/)). All software used in the course is open-source and freely available.

## Detailed Outline
### Block 1: Analysis of HDB Resale Prices I
1. Reproducible Science & Project Management (+ re-view of tidyverse basics)
  - Reading:
    - [Excuse me, do you have a moment to talk about version control?](https://peerj.com/preprints/3159/) **(done)**
    - [Happy Git with R](https://happygitwithr.com) (Chapter 1-15) **(done)**
    - [Reproducible research and quantitative geography](https://journals.sagepub.com/doi/abs/10.1177/0309132515599625) **(done)**
    - [Pro Git](https://git-scm.com/book/en/v2) (optional)

2. Exploratory Data Analysis (Univariate Statistics & Visualization)
  - Reading:
    - [Happy Git with R](https://happygitwithr.com) (Chapter 20-23) **(done)**
    - [Data Visualization Chapter 3](https://socviz.co/makeplot.html#makeplot)
    - Burt et al., *Elementary Statistics for Geographers*, (Chapter 3)

### Block 2: Analysis of HDB Resale Prices II
3. Sampling, Bootstrapping & Confidence Intervals
  - Reading:
    - Burt et al., *Elementary Statistics for Geographers*, (Chapter 6)
    - [Modern Dive Chapter 8](https://moderndive.com/8-sampling.html)
    - [Modern Dive Chapter 9](https://moderndive.com/9-confidence-intervals.html)
4. Correlation & Linear Regression
  - Reading:
    - Burt et al., *Elementary Statistics for Geographers*, (Chapter 4)
    - [Modern Dive Chapter 6](https://moderndive.com/6-regression.html)

### Block 3: Geodemographics of SG Neighborhoods I
5. Dimension Reduction (MDS/PCA)
  - Reading: 
    - Gatrell, Anthony C. “Multidimensional Scaling.” In *Quantitative Geography*. Routledge & Kegan Paul, 1981.
    - [Principal Component Analysis, Explained Visualy](http://setosa.io/ev/principal-component-analysis/)
    - [Wyly's notes on PCA](http://ibis.geog.ubc.ca/~ewyly/teaching/606_pca.pdf)
6. Dimension Reduction (T-SNE)
  - Reading:
    - [Van der Maaten's Google Tech Talk](https://www.youtube.com/watch?v=RJVL80Gg3lA&list=UUtXKDgv1AVoG88PLl8nGXmw)

**7. Break**

### Block 4: Geodemographic of SG Neighborhoods II
8. Clustering (non-spatial)
  - Reading:
      - Fortunato, F. [Community Detection in Graphs](https://arxiv.org/abs/0906.0612). Specifically section 4a-c.
      - Jain, A. [Data clustering: 50 years beyond K-means](https://doi.org/10.1016/j.patrec.2009.09.011)
      - Ester et al. [A Density-Based Algorithm for Discovering Clusters](https://www.aaai.org/Papers/KDD/1996/KDD96-037.pdf)
9. Clustering (spatial, including refresher on spatial data structures)
  - Reading:
      - Guo, D. [Regionalization with dynamically constrained agglomerative clustering and partitioning (REDCAP)](https://doi.org/10.1080/13658810701674970)
      - Poorthuis, A. [How to draw a neighborhood](https://doi.org/10.1111/gean.12143)


### Block 5: Spatial Statistics
10. Spatial Statistics I (Spatial Autocorrelation)
  - Reading:
      - TBA
11. Spatial Statistics II (Spatial Regression Modeling)
  - Reading:
      - TBA

### Block 6: Classification
12. Classification (logistic regression & SVM)
  - Reading:
      - TBA
13. Classification (overflow, possible excursion to deep learning)
  - Reading:
      - TBA
14. Final Project Studio
